### PR TITLE
Add linters for reStructured Text

### PR DESCRIPTION
**Pull request by languitar**
rst-lint and rstcheck

### CODE REVIEW

**Comment by renstrom** [comment]
I think @benekastah wants you to add [this](https://github.com/benekastah/neomake/blob/master/autoload/neomake/makers/ft/python.vim#L1) modeline to the top of the file.

**Comment by languitar** [comment]
Interesting, I adapted the json file and there the modeline is missing.

**Comment by renstrom** [comment]
I guess he's not very strict about it, I got asked to add it in one of my pull requests: https://github.com/benekastah/neomake/pull/70#issuecomment-86643860

**Comment by languitar** [comment]
Maybe this needs a linter added to neomake ;)

**Comment by benekastah** [comment]
Yeah, it's a fun irony that I haven't found a linter for vimscript that I could get working in neovim yet :)

**Comment by benekastah** [comment]
Thanks!

**Pull request merged**
