### PR TITLE
Reek maker for ruby files

### PR DESCRIPTION
**Pull request by neckhair**
[Reek](https://github.com/troessner/reek) detects code smells in Ruby files. This PR adds support to integrate detections in neovim.

### CODE REVIEW

**Comment by benekastah** [comment]
Thanks!

**Comment by neckhair** [comment]
Thanks for neomake! And thanks for merging.

**Comment by zamith** [comment]
Is it possible to only run this maker if reek is in the Gemfile? The reasoning is that I would have to consciously opt-in to having all of the warnings from reek, which are both more and more questionable than the one's in rubocop.

**Comment by neckhair** [comment]
I would rather check if the binaries (rubocop or reek) are present. I never have them in any Gemfile but always install them for all ruby versions. Or maybe add some configuration the deactivate reek or rubocop.

**Comment by zamith** [comment]
My suggestion of the Gemfile, was so that it could be controlled on a project basis, not ruby version. Maybe a `.neomakerc` file or something, to configure it per project? Not sure if there's such a thing already.

**Pull request merged**
