### PR TITLE
Add vim-airline extension.

### PR DESCRIPTION
**Pull request by renstrom**
Add statusline extension for vim-airline. The lines got a bit long, do you want me to wrap them?

It's that `E:4` to the right:
screen shot 2015-03-26 at 13 28 11

### CODE REVIEW

**Comment by benekastah** [comment]
This looks fine, but I'd rather we wrap these methods in a neomake setting to prevent adding things to people's statusline who don't want it. Something like:

```
function! airline#extensions#neomake#apply(...) abort
    if (get(g:, 'neomake_airline', 0)
        " All the other stuff here
    endif
endfunction
```

Same with the other function. Also, please copy the modeline from another file into this one. Thanks!

**Comment by renstrom** [comment]
Sure thing. Do you want the option enabled or disabled by default?

**Comment by benekastah** [comment]
My preference is to be pretty conservative with things that are done automatically. However, this feature would be difficult to discover if it was disabled by default. I'll let that be your call. I'm not an airline user myself.

**Comment by renstrom** [comment]
Right, I'll probably go with enabled by default since that's the behaviour you'd get with stock Syntastic and Airline.

Added an option now with some docs, not sure if it's enough though. Also, from what I can tell the `errorformat` must contain `%t` (and possibly others) to populate `neomake#statusline#LoclistStatus()`...?

**Comment by benekastah** [comment]
Yeah, currently `neomake#statusline#LoclistStatus()` isn't very sophisticated. Feel free to improve it if you want something more about it.

**Pull request merged**
