### PR TITLE
Default signs background highlight

### PR DESCRIPTION
**Pull request by eugen0329**
This pull request defines default colors corresponding to the sign column background, thus the default colors will look more natural

### CODE REVIEW

**Comment by benekastah** [comment]
Thanks!

**Comment by benekastah** [comment]
Looks like the `guifg` bit breaks vim 7.4. For practical reasons we try to keep neomake working on vim and neovim. I don't personally have any vim guis, so could you fix this?

**Comment by demon386** [comment]
I got warning after this patch.

```
line   47:
E421: Color name or number not recognized: ctermbg=-1 guibg=
line   48:
E421: Color name or number not recognized: ctermbg=-1 guibg=
line   49:
E421: Color name or number not recognized: ctermbg=-1 guibg=
line   50:
E421: Color name or number not recognized: ctermbg=-1 guibg=
Press ENTER or type command to continue
```

**Comment by casimir** [comment]
@demon386 If you're using GitGutter maybe you can help there #257.

**Comment by benekastah** [comment]
I reverted this, since it's causing problems.

**Comment by casimir** [comment]
@benekastah since it wasn't broken for everyone could it be an opt-in feature instead of nuking it?

**Comment by eugen0329** [comment]
Fish can't be half fresh. If a problem appears at least for one user - it is nothing more than a bug, so this is a bad idea to make this feature optional. Nevertheless, I fix this bugs as soon as possible.

**Comment by benekastah** [comment]
Thanks @eugen0329!

**Comment by casimir** [comment]
Just to clarify by optional I meant guarded by a `has('nvim')` or a Vim version check.

**Comment by blueyed** [comment]
I don't think it has something to do with Vim vs Neovim, but more with the colorscheme being used.

**Comment by blueyed** [comment]
See https://github.com/neomake/neomake/pull/456 for a follow-up.

**Pull request merged**
