### PR TITLE
Append captured lines from makers correctly

### PR DESCRIPTION
**Pull request by sanmiguel**
Fixes issue #153
As per https://github.com/neovim/neovim/issues/3555

### CODE REVIEW

**Comment by sanmiguel** [comment]
Hi - I am not sure if this is the appropriate way to do this: you were using `extend()` which implies you expect `lines` to sometimes be a dict, but I couldn't find anywhere that might happen.

Anyway - I used the solution @ZyX-I laid out in neovim/neovim#3555 for correctly appending to rebuild lines even if they arrive in partial flushes.

**Comment by benekastah** [comment]
If the last line captured was a full line rather than a partial line, won't this result in two lines being concatenated together and treated as one line? (Forgive me if I'm mistaken, I haven't kept fully abreast of the changes made in neovim since I implemented this).

**Comment by sanmiguel** [comment]
Apologies I have been busy lately and haven't had a chance to reply to this.

This works because `nvim` does something I find a little surprising (IMHO) when handing flushed lines to a jobcontrol callback. @tarruda described it quite succinctly in neovim/neovim#3555 : 

```
It's simple: for every list you receive in a callback, all items except the first represent newlines. 
```

When a complete line (i.e. some text followed by a newline) is flushed to stdout (or stderr) and nvim, it's presented to the callback as `[ 'some text', '' ]`. We can see this in action by running the following `jobcontrol.vim` (again taken from neovim/neovim#3555) :

``` vim
let g:full_stdout = ['']
let g:raw_stdout = []
function! s:JobHandler(job_id, data, event)
  if a:event isnot# 'stdout'
    echo 'g:raw_stdout: ' . string(g:raw_stdout)
    return
  endif
  call add(g:raw_stdout, a:data)
  let g:full_stdout = g:full_stdout[:-2] + [g:full_stdout[-1] . get(a:data, 0, '')] + a:data[1:]
endfunction
let s:callbacks = {
      \ 'on_stdout': function('s:JobHandler'),
      \ 'on_exit': function('s:JobHandler')
      \ }

let job = jobstart(['bash', '-c', 'echo ..; sleep 0.6; echo ..; sleep 0.6; echo ..'], s:callbacks)
```

```
$ nvim -u NONE -S jobcontrol.vim
...
[['..', ''], ['..', ''], ['..', '']]
```

So we can see the raw lines we receive for each full line are actually presented as the text, followed by an empty string representing a newline.

Actually even the way it was suggested to solve in neovim/neovim#3555 is not 100% accurate as, in cases like the example, what we actually end up with in `g:full_stdout` is `[ '..', '..', '..', '' ]` i.e. an extra blank line at end. Mostly this won't cause an issue but if your `maker.errorformat` does something with blank lines it might cause an issue. We could probably do something durty just to lop off a single trailing blank line (if one exists) but something more elegant must be possible....

**Comment by sanmiguel** [comment]
Rock on! Thanks @benekastah !

**Comment by benekastah** [comment]
Thanks for the explanation! Let's see if the trailing newline thing becomes a problem in the real world.

**Comment by sanmiguel** [comment]
You're welcome! It took me so long to answer because when you asked that question I couldn't immediately explain why it worked beyond "because someone else says it does". Had to experiment a bit, which needed time. I'm thinking the erroneous trailing blank line is a small price to pay and will be reasonably unlikely to cause any problems IRL.

**Pull request merged**
